name: Deploy to EC2

on:
  push:
    branches:
      - main  # Set to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
            switches: -avzr --delete
            path: ./*
            remote_path: /var/www/my-app/
            remote_host: ec2-54-172-222-95.compute-1.amazonaws.com
            remote_user: ec2-user
            remote_key: "${{ secrets.MY_SECRETE_KEY }}"
