name: Deploy to EC2

on:
  push:
    branches:
      - main  # Set to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
            switches: -avzr --delete
            path: ./*
            remote_path: /home/ec2-user/app
            remote_host: ec2-54-167-123-219.compute-1.amazonaws.com
            remote_user: ec2-user
            remote_key: "${{ secrets.MY_SECRETE_KEY }}"

    - name: Start Server
      uses: appleboy/ssh-action@master
      with:
            host: ec2-54-167-123-219.compute-1.amazonaws.com # Your EC2 instance's public IP or domain
            username: ec2-user # Default is 'ec2-user' for Amazon Linux
            key: ${{ secrets.MY_SECRETE_KEY }}  # SSH private key
            script: |
                cd /home/ec2-user/app/MyRestartBlog  # Change to the directory where your app is
                npm install 
                npm run start 